# Generated by Django 4.1.5 on 2023-02-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_brand_name_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=20, verbose_name='flag'),
        ),
    ]
