# Generated by Django 4.1.5 on 2023-02-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Sale', 'Sales'), ('Feature', 'Feature'), ('New', 'New')], max_length=20, verbose_name='flag'),
        ),
    ]
