# Generated by Django 4.1.5 on 2023-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_active_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.TextField(max_length=500, verbose_name='Subtitle'),
        ),
    ]
