# Generated by Django 4.1.5 on 2023-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_ar',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=20, null=True, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_en',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=20, null=True, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ar',
            field=models.TextField(max_length=500, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sales'), ('Feature', 'Feature')], max_length=20, verbose_name='flag'),
        ),
    ]
