# Generated by Django 4.1.5 on 2023-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Sale', 'Sales'), ('New', 'New'), ('Feature', 'Feature')], max_length=20, verbose_name='flag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag_ar',
            field=models.CharField(choices=[('Sale', 'Sales'), ('New', 'New'), ('Feature', 'Feature')], max_length=20, null=True, verbose_name='flag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag_en',
            field=models.CharField(choices=[('Sale', 'Sales'), ('New', 'New'), ('Feature', 'Feature')], max_length=20, null=True, verbose_name='flag'),
        ),
    ]
