# Generated by Django 4.1.5 on 2023-04-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_active_alter_product_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='product.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='product.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ar',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
