# Generated by Django 4.1.5 on 2023-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_brand_ar_product_brand_en_product_price_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flag_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle_en',
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'Feature'), ('New', 'New'), ('Sale', 'Sales')], max_length=20, verbose_name='flag'),
        ),
    ]
