# Generated by Django 4.1.5 on 2023-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_product_brand_ar_remove_product_brand_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'Feature'), ('Sale', 'Sales'), ('New', 'New')], max_length=20, verbose_name='flag'),
        ),
    ]
