# Generated by Django 4.1.5 on 2023-07-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_product_flag_wishproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishproduct',
            name='product_wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', to='product.product'),
            preserve_default=False,
        ),
    ]
