# Generated by Django 4.1.5 on 2023-04-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.utils.genirite_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('code', models.CharField(default=orders.utils.genirite_code.genirite_code, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typy', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tybe', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Business', 'Business'), ('Acadmy', 'Acadmy'), ('Other', 'Other')], max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adresse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
