# Generated by Django 4.1.5 on 2023-02-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=20)),
                ('email_us', models.EmailField(max_length=30)),
                ('about', models.TextField(max_length=1000)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('goo_link', models.URLField(blank=True, null=True)),
                ('emails', models.CharField(max_length=30)),
                ('phonse', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
    ]
