# Generated by Django 4.1.5 on 2023-03-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='call_us',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email_us',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='goo_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='insta_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tw_link',
        ),
    ]
