# Generated by Django 4.1.5 on 2023-05-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_company_call_us_remove_company_email_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
