# Generated by Django 4.1.5 on 2023-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='totla',
            new_name='total',
        ),
    ]
