# Generated by Django 4.1.5 on 2023-02-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.utils.genirite_code


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_brand_slug'),
        ('orders', '0004_cart_cart_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Inprogress', max_length=12, verbose_name='cart_status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery_date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='odrder_code',
            field=models.CharField(default=orders.utils.genirite_code.genirite_code, max_length=12, verbose_name='odrder_code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order_date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Recevied', 'Recevied'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Recevied', max_length=12, verbose_name='order_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odere_detail', to='orders.order', verbose_name='order_detail'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='total'),
        ),
    ]
