# Generated by Django 4.1.5 on 2023-05-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_detail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_detail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_detail', to='orders.cart', verbose_name='cart'),
        ),
    ]
