# Generated by Django 4.1.5 on 2023-05-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_flag'),
        ('orders', '0009_remove_cart_detail_product_cart_detail_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_detail',
            name='product_cart',
        ),
        migrations.AddField(
            model_name='cart_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='product.product', verbose_name='product'),
        ),
    ]
